---
title: "exam"
author: "Rhosane Santos"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(asaur)
df <- prostateSurvival
df
```
```{r}
summary(df)
hist(df$survTime)
sum(is.na(df$status))
```

How many events, how many censored data points?
```{r}
table(df$status)
```

## Kaplan-Meyer estimator
```{r}
library(survival)
#df$status[df$status == 0] <- 2
df <- df[df$status != 2, ]
fit.KM <- survfit(Surv(survTime, status) ~ 1, data = df)
summary(fit.KM)
```

Question: what is the median survival time?
```{r}
fit.KM
```
We see the probability of surviving after the diagnosis in days.
```{r}
plot(fit.KM, mark.time = TRUE,
     main = "Kaplan-Meier estimator",
     ylab = "Survival probability",
     xlab = "time (days)")
```
## Nelson-AAlen estimator
It gives the same results as the Kaplan-Meier estimator.
```{r}
fit.NA <- survfit(Surv(survTime, status) ~ 1, data = df, type = "fh")
summary(fit.NA)
```
```{r}
fit.NA
```

# Nonparametric comparison of three samples

## Plotting the 3 curves
```{r}
sfit <- survfit(Surv(survTime, status) ~ stage, data = df)
sfit

survdiff(Surv(survTime, status) ~ stage, data = df)
```
```{r}
plot(sfit, col = c("black", "red"))
```
